application: kurohailo
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

  
- url: /static/image
  static_dir: ReactClient/static/image
- url: /static/js
  static_dir: ReactClient/static/js
- url: /static/css
  static_dir: ReactClient/static/css
- url: /static/media
  static_dir: ReactClient/static/media

- url: /scripts
  static_dir: scripts
- url: /images
  static_dir: images

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"